name: xaj
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - numpy
  - numba
  - pandas
  - scikit-learn
  - deap
  - spotpy=1.5.14
  - seaborn
  - tqdm
  - pytest
  - pip
  - pip:
    - hydrodataset
